### PR TITLE
Switch from TravisCI/Appveyor to gh actions

### PR DESCRIPTION
**Pull request by coatless**
This PR attempts to switch away from using TravisCI and Appveyor to using [GitHub Actions for R](https://github.com/r-lib/actions) per discussion in rOpenSci Slack with @sckott. 

What's missing:

- `GITHUB_TOKEN` needs to be set under the repository `secret` settings.
    - Setup here: https://github.com/ropensci/rorcid/settings/secrets

- Verification that `libv8-dev` isn't needed.

- Re-enable build status in rOpenSci's slack.

### CODE REVIEW

**Comment by coatless** [comment]
Sadly, this PR will have to be submitted by a collaborator.

> Only repository collaborators may create workflows.

Per: https://github.com/ropensci/rorcid/actions/new

**Comment by sckott** [comment]
do you mind if I rebase when merging?

**Comment by coatless** [comment]
@sckott no preference. But, how about a squash and merge commit? This will take all of the commits above and place it into a single commit.

**Comment by sckott** [comment]
woops, yes, that's what i meant

**Comment by coatless** [comment]
Sounds good! 👍

**Pull request merged**
